<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [59]:
c = 20
assert c >= 0 # condition is that c is greater than or equals to 0. if value of b becomes negative, assert will stop the 
# programme from running. so should not get assertation error 


In [55]:
assert b >= 0
x = (-1)*3 # need to define b first bfr asserting condition for b
print(b)

AssertionError: 

In [57]:
b = (-1)*2
assert(b >= 0) # you get an assertation error bcos b would be -2 
print(b)

AssertionError: 

### 1.2 try-except

In [13]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2              # here you are converting the input (number=input) into an integer. so there is an error
print(f'The square of {number} is {square}!') # bcos you cant convert hello into integer. 


Give me a number and I will calculate its square.hello


ValueError: invalid literal for int() with base 10: 'hello'

In [53]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!') # when there is an error, python goes to the except block to handle the 
except: #error. does not work if there is an error in the code itself. error has to be caused by wtvr was input in line 2
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.hello
Oh oh! I cannot square hello!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [15]:
def funny_add(a, b, c=1): # optional argument of c=1 if c is not specified 
    return a + 10*b + 100*c
funny_add(1,2) # add a and 10*b. '1' is default, '2' is positional 

121

In [16]:
funny_add(a=30,b=15,c=32)

3380

In [17]:
funny_add(1,1,) # optional argument where c=1 is taken as the defined value when c is not specified 

111

In [18]:
funny_add(a=45,6,7) # positional cannot be after keyword bcos python needs to set parameter for the argument which won't 
                    # work with positional after keyword

SyntaxError: positional argument follows keyword argument (2117656067.py, line 1)

In [19]:
funny_add(7,c=30,b=2)

3027

### 2.2 Docstrings

In [20]:
help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)



In [21]:
def funny_add(a, b, c=1): 
    '''
    A test function to demonstrate how  
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c

### 2.3 Function are first class citizens

function is like getting milk. function is telling someone to go get milk. the argument is getting milk. so if my function is go to the supermarket. then passing on the argument to another function would be go to the supermarket(function1) then go get milk(function 2). pass argument of getting milk from function 1 to function 2? 

In [22]:
def my_function(angle, trig_function): # function 1 which  I defined as my_function
        return trig_function(angle) # putting argument trig_function 
    # python 

# Let's use the function
my_function(np.pi/2, np.sin)        
#> 1.0
my_function(np.pi/2, np.cos)        
#> 6.123233995736766e-17
my_function(np.pi/2, lambda x: np.cos(2*x))  
#> -1.0

-1.0

### 2.4 More unpacking

In [23]:
x, *y, z = np.array([1, 2, 3, 4, 5]) # prints everything in the middle of the first and the last element 
print(x, y, z) 


1 [2, 3, 4] 5


In [24]:
x, *y , z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # prints from 2-9 in a different array
print(x,y,z)

1 [2, 3, 4, 5, 6, 7, 8, 9] 10


In [25]:
x, *_, y = [1, 2, 3, 4, 5] # cancels everything in the middle 
print(x, y)

1 5


## Exercise 1 :  A better calculator I

In [26]:
def add(number_1,number_2):
    addition = number_1 + number_2
    return addition

def substract(number_1,number_2):
     return number_1 - number_2
    
def multiply(number_1,number_2):
    return number_1*number_2 

def divide(number_1,number_2):
    assert np.all(number_2!=0) # all elements are not equal to 0 using !=
    return number_1/number_2 
    




In [31]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
add(x,y)

array([100, 100, 100, 100, 100])

In [32]:
substract(x,y)

array([-28, -32, -12,  52, -46])

In [33]:
multiply(x,y)

array([2304, 2244, 2464, 1824, 1971])

In [34]:
divide(x,y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

## Exercise 2 :  A better calculator II

In [77]:
def add(number_1,number_2):
    addition = number_1 + number_2
    return addition

def substract(number_1,number_2):
     return number_1 - number_2
    
def multiply(number_1,number_2):
    return number_1*number_2 
 
def divide(number_1,number_2):
    try:
        assert np.all(number_2 != 0) # if it does not fulfil this function, then it will always be an error and it will 
        return number_1/number_2 # go to except block 
    except:
        print("BOOOOOO!!") # note: cant use except w return exit() bcos it just kills the kernel all together 
    

In [60]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
z=np.array([-1,30,4,5,2])
a= np.array([20,30,0,15,3])
add(x,y)

array([100, 100, 100, 100, 100])

In [36]:
substract(x,y)

array([-28, -32, -12,  52, -46])

In [38]:
multiply(x,y)

array([2304, 2244, 2464, 1824, 1971])

In [39]:
divide(x,y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

In [76]:
divide(x,z) # still works w negative number.. only won't work with element being 0

BOOOOOO!!


In [78]:
divide(x,a) # shouldnt i get boo??

BOOOOOO!!


In [3]:
import numpy as np