<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [5]:
def greeting(name):                                 # here you are defining the function (greeting). 
    if name == 'Batman':                            # there is no output because you are just setting the 'equation'
        return 'Hello Batman! So, nice to meet you!'# like f(x) = x+3 but there is no output because no value of x is
    else:                                           # given yet
        return f'Hello {name}!'                   

print(greeting('Batman'))
print(greeting('Niki'))


Hello Batman! So, nice to meet you!
Hello Niki!


In [7]:
def greeting(name):                                 
    if name == 'Batman':                         
        return 'Hello Batman! So, nice to meet you!'# without else 
    return f'Hello {name}!'       # return keyword jumps out of the function with the return value
                                  #if it was false then when name is Batman then it would not read the code
print(greeting('Batman'))         # after the return. python continues to read the code after the return keyword so do not
print(greeting('Niki'))           # need else 

Hello Batman! So, nice to meet you!
Hello Niki!


In [8]:
print(greeting("Niki")) # here name is the x 

Hello Niki!


In [7]:
greet=greeting(name='Super Man') # set a variable to the function 
print(greet)  # basically the same thing as print(greeting(name='')) with an extra step


Hello Super Man!


In [8]:
print(greeting(name='Nikita'))

Hello Nikita!


In [16]:
print(greeting('Nik')) # DONT NEED NAME= !!!!!

Hello Nik!


In [2]:
def basic_stats(numbers):  # numbers is the variable you are doing stuff with
    np_numbers =np.array(numbers) # local variable only exists in the function you have defined. np_numbers only exists within function basic_stats
    return np_numbers.min(), np_numbers.max(), np_numbers.mean() # returns min, max and mean that is stored under the VARIABLE np_numbers
potato = 23, 45, 46, 345, 355 
basic_stats(potato) 

(23, 355, 162.8)

In [6]:
basic_stats([1, 2, 3, 4, 5])

(1, 5, 3.0)

In [7]:
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5]) #  why am i making list_min, list_max and list_mean a variable again?

In [1]:
def sky(colour):
    if colour == 'blue':
        return 'sky is blue!'
    return f'wow look the sky is {colour}, uwu'
print(sky('orange')) # colour is a place holder so you can just put orange

'wow look the sky is orange, uwu'

### 1.2 Named functions that don’t return

when functions returns a value, the value is returned via a return statement to the caller of the function, after being implicitly converted to the return type of the function in which it is defined. 

### 1.3 Anonymous functions

In [7]:
(lambda x: x+1)(2)

3

In [9]:
my_short_function = lambda name: f"Hello {name}!"
my_short_function(name="Super Man")

'Hello Super Man!'

In [10]:
numbers=[[9, 0, 10],
         [8, 1, 11],  # stored 2d list in variable called numbers 
         [7, 2, 12],
         [6, 3, 13], # called function sorted. sorting numbers in the small list in ascending order 
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [13]:
sorted(numbers, key=lambda x: x[1])

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [15]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!' # argument that has a defined value is called optional argument 
    else:                                            # default value can be specified using assignent operator (eg =). 
        return f'Hello {name}!' 
greeting()                                           # so when you call the function there is no need to provide a value 

'Hello no one!'

In [17]:
def time(availability='free'):  # defining argument with defined value of potato 
    if availability == 'free': # output is if statement bcos availability has alr been defined as free which fulfils if 
        return f'I am {availability} today!' # statement 
    else:
        return f'I will be {availability} today'
time()

'I am free today!'

In [18]:
def time(availability='potato'): 
    if availability == 'free': 
        return f'I am {availability} today!' 
    else:
        return f'I will be {availability} today'
time()

'I will be potato today'

In [22]:
def greeting(name):                                 # different from here where function is just defined as name with
    if name == 'Batman':                            # name having no value being defined 
        return 'Hello Batman! So, nice to meet you!'# so need to put in a value of name for it to work
    else:                                           
        return f'Hello {name}!'  
greeting() # will not work 
greeting('sarah') 

TypeError: greeting() missing 1 required positional argument: 'name'

In [23]:
def greeting(name):
    if name == 'Batman':                          
        return 'Hello Batman! So, nice to meet you!'
    else:                                           
        return f'Hello {name}!'  
greeting('sarah')  # name given the value of 'sarah'

'Hello sarah!'

In [16]:
?print 

In [24]:
print('I', 'am', 'Batman!')                 # here value is defined 

print('I', 'am', 'Batman!', sep='---')  # print can be specific and optional as well 

I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

In [27]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'
greeting('panda')




'Hello panda!'

Return keyword jumps out of the function which is being defined to return a value. As a result, python will continue reading the next lines of code after return keyword which is why else is not needed for the code to work.  

## Exercise 2 :  Calculator functions

In [61]:
def add(number_1,number_2):
    addition = number_1 + number_2
    return addition

def substract(number_1,number_2):
     return number_1 - number_2
    
def multiply(number_1,number_2):
    return number_1*number_2 

def divide(number_1,number_2):
    if np.any(number_2 > 0):  # array has a lot of elements so use np.any to make sure that if any element is zero then
        return number_1/number_2 # the if statement will not proceed
    return exit()



In [48]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
add(x,y)

array([100, 100, 100, 100, 100])

In [53]:
substract(x,y)

array([-28, -32, -12,  52, -46])

In [52]:
multiply(x,y)

array([2304, 2244, 2464, 1824, 1971])

In [62]:
divide(x,y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

In [39]:
def add(number,numbers):
    return number + numbers         # do not need to create a new variable 
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
add(x,y)

array([100, 100, 100, 100, 100])

## Exercise 3 :  max_info() with NumPy

In [65]:
def max_info(numbers):
    return np.max(numbers), np.argmax(numbers)
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
max_info(numbers)




(83, 2)

In [66]:
def max_info(potato):   # variable is called potato which is a list 
    return np.max(potato), np.argmax(potato) # finding the max no. and index in variable potato 
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49] # new variable number that contains a set 
max_info(numbers) # OR you can do max_inf0(potato=numbers) which gives the same output 


(83, 2)