<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [1]:
py_fruits = ['Mango', 'Apple', 'Pear', 'Kiwi']    #storing data using python list
py_fruit_colours = ['Yellow', 'Red', 'Green', 'Brown']


In [3]:
np_fruits = np.array(["Mango", "Apple", "Pear", "Kiwi"]) #storing data using numpy array 
np_fruit_colours = np.array(["Yellow", "Red", "Green","Brown"])

In [11]:
fruit_info = {"Mango": "Yellow", #storing data using dictionary
                  "Apple": "Red",
                  "Pear": "Green",
                  "Kiwi": "Brown"
                  }

### 1.2 Accessing data from a list (or array)

In [6]:
print(py_fruits[3])


Kiwi


In [8]:
print(py_fruit_colours[3])

Brown


In [10]:
print(np_fruits[-2])

Pear


### 1.3 Accessing data from a dictionary

In [13]:
print(fruit_info["Mango"])


Yellow


In [15]:
fruit_info.keys()

dict_keys(['Mango', 'Apple', 'Pear', 'Kiwi'])

In [16]:
fruit_info.values()

dict_values(['Yellow', 'Red', 'Green', 'Brown'])

### 1.4 Higher dimensional lists

In [23]:
fruit_info = [['Mango', 'Yellow'],
              ['Apple', 'Red'],
              ['Pear', 'Green'],
              ['Kiwi', 'Brown']]

## 2 Lists vs. Arrays

### 2.1 Size

In [34]:
py_list_2d = [[1,'Mala'], [2,'Hotpot'], [3,'Fried Rice'], [4,'Mee Rebus'],
             [5,'Pasta'], [6,'French fries'], [7,'Green curry']]
np_array_2d = np.array(py_list_2d)


In [32]:
len(py_list_2d)

7

In [35]:
np_array_2d.shape

(7, 2)

### 2.2 Arrays are fussy about type

In [37]:
py_list = [1,4,'Maincoon']
np.array(py_list)


array(['1', '4', 'Maincoon'], dtype='<U11')

### 2.3 Adding a number

In [38]:
py_list = [2, 4, 15, 63]
np_array = np.array(py_list)


In [41]:
py_list +6 #does not work with python

TypeError: can only concatenate list (not "int") to list

In [40]:
np_array +6

array([ 8, 10, 21, 69])

### 2.4 Adding another list

In [42]:
py_list_uno = [3, 5, 6, 23, 76]
py_list_duos = [65, 743, 634, 883,82738]

np_array_uno = np.array(py_list_uno)
np_array_duos = np.array(py_list_duos)


In [44]:
py_list_uno + py_list_duos

[3, 5, 6, 23, 76, 65, 743, 634, 883, 82738]

In [45]:
np_array_uno + np_array_duos

array([   68,   748,   640,   906, 82814])

### 2.5 Multiplying by a Number

In [46]:
py_list_ein = [3, 63, 9327, 823]
np_array_ein = np.array(py_list_ein)

In [47]:
py_list_ein*4 #repeat of list 4 times

[3, 63, 9327, 823, 3, 63, 9327, 823, 3, 63, 9327, 823, 3, 63, 9327, 823]

In [48]:
np_array_ein*6 #numbers multiplied by 6

array([   18,   378, 55962,  4938])

### 2.6 Squaring

In [49]:
py_list_zwei = [3, 63, 9327, 823]
np_array_zwei = np.array(py_list_zwei)


In [50]:
py_list_zwei**2 #can't do

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [52]:
np_array_zwei**2

array([       9,     3969, 86992929,   677329])

### 2.7 Asking questions

In [53]:
py_list_drei = [3, 63, 9327, 823]
np_array_drei = np.array(py_list_drei)


In [54]:
py_list_drei!= 45

True

In [55]:
py_list_drei< 73 # does not work

TypeError: '<' not supported between instances of 'list' and 'int'

In [57]:
np_array_drei>=72

array([False, False,  True,  True])

### 2.8 Mathematics

In [58]:
py_list = [3, 63, 9327, 823]
np_array = np.array(py_list_drei)

In [59]:
sum(py_list)

10216

In [60]:
max(py_list)

9327

In [62]:
np_array.sum()

10216

In [64]:
np_array.mean()

2554.0

## Exercise 1 :  Total recall?

1. Similarities: can find max and min of both array and list. way to access data in array and list is the same.
2. Differences: You can do addition in array but not in list. Multiplication in list means that the list is 'duplicated' that many times but in array each number in the array is multiplied by the number.
3. Dictionary is a way to store data where you can assign values to the keys.



## Exercise 2 :  Index me

In [68]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
                
print(py_list[0],py_list[2],py_list[4],py_list[6],py_list[8])   # Print odd numbers




a1 c3 e5 g7 i9


## Exercise 3 :  Capitalise Heros

In [69]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()            
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper() 
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()

print(superhero_info)




{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [71]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  
np_array = np.array(numbers)



In [73]:
np_array.min()

1

In [75]:
np_array<=1 #9 trues, therefore there are 9 ones

array([False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False])