<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [1]:
py_list=['pillow','potato','peanut','paper','pecan','parmesan','parrot','peacock','panda','pancake']
np_array=np.array(py_list)

x = py_list 
y = np_array


In [3]:
x[2:10:2]

['peanut', 'pecan', 'parrot']

In [5]:
x[3:]

['paper', 'pecan', 'parmesan', 'parrot']

### 1.2 Subsetting by masking (Arrays only)

In [14]:
np_array = np.array([43, 634, 6342, 64, 2, 435, 64])
my_mask = np_array<4
print(my_mask)

[False False False False  True False False]


In [11]:
np_array[my_mask]

array([2])

In [15]:
np_array[np_array>45]

array([ 634, 6342,   64,  435,   64])

In [16]:
np_array[np_array==64] #will list 64 twice

array([64, 64])

In [20]:
np_array[~(np_array==64)]

array([  43,  634, 6342,    2,  435])

In [22]:
np_array[(np_array>40) & (np_array<65)]

array([43, 64, 64])

In [26]:
np_array[(np_array<10) | (np_array<65)]

array([43, 64,  2, 64])

### 1.3 Indexing & Slicing 2D Lists

In [27]:
py_list_2d = [[1,'Mala'], [2,'Hotpot'], [3,'Fried Rice'], [4,'Mee Rebus'],
             [5,'Pasta'], [6,'French fries'], [7,'Green curry']]


In [28]:
py_list_2d[4]

[5, 'Pasta']

In [29]:
py_list_2d[4][0]

5

In [30]:
py_list_2d[:5]

[[1, 'Mala'], [2, 'Hotpot'], [3, 'Fried Rice'], [4, 'Mee Rebus'], [5, 'Pasta']]

In [31]:
py_list_2d[:3][0]

[1, 'Mala']

### 1.4 Indexing & Slicing 2D Arrays

In [32]:
np_array = np.array(py_list_2d)


In [33]:
np_array[3]

array(['4', 'Mee Rebus'], dtype='<U12')

In [34]:
np_array[3,0]

'4'

In [37]:
np_array[:3]

array([['1', 'Mala'],
       ['2', 'Hotpot'],
       ['3', 'Fried Rice']], dtype='<U12')

In [38]:
np_array[3:6,0]

array(['4', '5', '6'], dtype='<U12')

In [39]:
np_array[:,0]

array(['1', '2', '3', '4', '5', '6', '7'], dtype='<U12')

### 1.5 Growing lists

In [40]:
x= [1]*10
print(x)


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [42]:
x=[1]
x= x + [2]
x = x + [3]
print(x)

[1, 2, 3]


In [46]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
print(x)

[1, 2, 3, 4]


In [48]:
x=[10]
x+= [4,6,8]
print(x)

[10, 4, 6, 8]


In [49]:
x=[34]
x= [43,6,6] +x
print(x)

[43, 6, 6, 34]


In [55]:
x=[1]
x.append(2)
x.append(43)
x.append('apple')
print(x)

[1, 2, 43, 'apple']


## 2 Some loose ends

### 2.1 Tuples

In [56]:
beans=(45, 64, 623)

In [58]:
print(beans[2])

623


In [59]:
beans[1]+14

78

In [60]:
beans[1] = -1

TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [62]:
h = [5,9,93]
y=h.copy()
print(y)

[5, 9, 93]


## Exercise 1 :  Total recall?

| $Term$  | $Brief Description$  |
|---|---|
| $Subsetting$ | is the action of selecting from a list or array |
| $Indexing$ | selecting a specific element |
| $Slicing$ | selecting a number of elements in a range  |
| $Masking$ | showing elements that are not 'masked'  |




## Exercise 2 :  Show me the ‘odd’ letters

In [84]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

array_1 = np_array_2d[:, 0].astype(int)%2 # identify odd numbers
print(array_1) #check array
mask = array_1 == 1 # create mask for odd numbers
np_array_2d[mask][:,1] # subset second elements

[1 1 0 0 1 1 0 0 0 1]


array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')